### PR TITLE
Adding links section

### PR DESCRIPTION
**Pull request by peteruithoven**
Adding a "Links" section on the top of the Documents page.

### CODE REVIEW

**Comment by rikva** [comment]
Very cool that you're doing this. Looking good so far 👍

**Comment by peteruithoven** [comment]
By tagging on the links as extra context to the documents [ListView](https://docs.djangoproject.com/en/1.10/ref/class-based-views/generic-display/#listview) I understand we miss out on things like pagination, but I think if we get that many links we should create a separate page for it anyway.

**Comment by peteruithoven** [comment]
I think this is ready, please let me know if you want me to improve things.

**Comment by rikva** [comment]
> By tagging on the links as extra context to the documents [ListView](https://docs.djangoproject.com/en/1.10/ref/class-based-views/generic-display/#listview) I understand we miss out on things like pagination, but I think if we get that many links we should create a separate page for it anyway.

Agreed, and at some point I think we should add categories too.

**Comment by rikva** [comment]
Nice work 👍

**Pull request merged**
