### PR TITLE
Admin access to transport schedule

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #107

### CODE REVIEW

**Comment by peteruithoven** [comment]
Thanks for the reviews! :)

**Comment by peteruithoven** [comment]
@rikva could you also deploy these changes?

**Comment by rikva** [comment]
They were already deployed yesterday?

**Comment by peteruithoven** [comment]
Ah apologies, I was checking the wrong thing to verify that. Confused the transport ride page for the distribution shift page.

**Pull request merged**
