### PR TITLE
Changed transport coordinator field

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes:  #56

### CODE REVIEW

**Comment by rikva** [comment]
Do we want to copy the data from past order rounds to the new field?

**Comment by rikva** [comment]
(in that case we could write a data migration)

**Comment by peteruithoven** [comment]
Ah I already wrote down the current fields, so I could migrate manually. It
didn't seem like enough data to look into data migration.

**Comment by rikva** [comment]
Ah, that's fine by me. I will merge now, but prefer to deploy after the current order round has finished, is that ok with you?

**Comment by peteruithoven** [comment]
Yeah, that makes sense to me.

**Pull request merged**
