### PR TITLE
Enforce unique OrderRounds

### PR DESCRIPTION
**Pull request by peteruithoven**
Fixes: #25

### CODE REVIEW

**Comment by peteruithoven** [comment]
I'm running into this issue:
```
sqlite3.IntegrityError: UNIQUE constraint failed: ordering_orderround.collect_datetime
```
I'm assuming this is because there are existing OrderRounds with not equal dates.

**Comment by peteruithoven** [comment]
When I removed the Order round with equal dates the migrate went successfully.

**Comment by peteruithoven** [comment]
I'm assuming this fails because unit tests create OrderRounds on the same date (now)?
https://github.com/rikva/voko/blob/master/webapp/ordering/tests/test_models.py#L60
https://github.com/rikva/voko/blob/master/webapp/ordering/tests/factories.py#L17

**Comment by rikva** [comment]
> I'm assuming this fails because unit tests create OrderRounds on the same date (now)?
> https://github.com/rikva/voko/blob/master/webapp/ordering/tests/test_models.py#L60
> https://github.com/rikva/voko/blob/master/webapp/ordering/tests/factories.py#L17

Yeah it looks like the `collect_datetime` is autofilled and it's not unique.

**Comment by peteruithoven** [comment]
I'm closing this one, it's probably not the right approach.

**Pull request closed without merging**
