### PR TITLE
Anonymous order rounds and accounts api 

### PR DESCRIPTION
**Pull request by peteruithoven**
See: #50

What do you think of this Rik?
Does this impact the Privacy statement?

The accounts api is probably way more controversial so I'd be happy to split up this PR in a seperate PR per API endpoint.

### CODE REVIEW

**Comment by rikva** [comment]
I *think* this is all non-identifiable information and should not breach our privacy statement.

**Comment by peteruithoven** [comment]
Good point. That is also kind of what I was going for. 

For easier manual processing I've added a csv endpoint. I'm not sure about how I did that utils.py.

**Comment by peteruithoven** [comment]
@rikva I don't want to push but I'd love to get these numbers and be able to present them during the ALV.

**Comment by rikva** [comment]
Sorry, I forgot about this PR. I would like to add one thing: restriction of the views to the relevant group(s) (e.g. "IT"? you are member of that group). Should be easy using the `GroupRequiredMixin`.
The data should not infringe on anybody's privacy but I would feel more comfortable when it's not readable by everyone...

**Comment by peteruithoven** [comment]
I was actually hoping to use these api's for a members accessible dashboard with some readable live graphs, but I guess it might be wise to start with limited accessibility. I don't think this data is purely a IT thing though. I'd like to also share this with Promo.

**Comment by peteruithoven** [comment]
I found the [documentation on GroupRequiredMixin](https://django-braces.readthedocs.io/en/latest/access.html#grouprequiredmixin) a bit unclear but I assumed that when you defined multiple groups it would require membership of all those groups. So I've written a little test and use [UserPassesTestMixin](https://django-braces.readthedocs.io/en/latest/access.html#userpassestestmixin).

**Comment by rikva** [comment]
No, it implements `or` logic, you basically rewrote that yourself now 😆

**Comment by rikva** [comment]
Deployed!

**Comment by peteruithoven** [comment]
Dammit :laughing: I'll do a new PR simplifying that. 
Thanks for the reviews and deploy!

**Pull request merged**
